version: "3.7"
services:
  postgres:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    platform: linux/arm64

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - postgres
